### ISSUE TITLE
decrease height of section

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/website#43] opened 2017-09-30 18:38 UTC
on homepage this is occupying too much height
![screenshot from 2017-10-01 00 07 45](https://user-images.githubusercontent.com/14791631/31048538-a1177cae-a63c-11e7-896c-f18d03febbe9.png)

**Comment by pranay414** [comment] 2017-09-30 18:57
Hey, I would like to take up this issue.

**Comment by codehimanshu** [comment] 2017-09-30 18:58
sure, go ahead.

**Comment by pranay414** [comment] 2017-09-30 19:00
Can you tell me how to go to this page?

**Comment by codehimanshu** [comment] 2017-09-30 19:02
This is the homepage. After installation of project, head over to http://localhost:8000
this file is used as template: website/client/templates/client/index.html

**Comment by pranay414** [comment] 2017-09-30 19:06
I am getting Google maps page with "JSS College" marked on it.

**Comment by codehimanshu** [comment] 2017-09-30 19:12
check the access to static files in your developer console. might be we missed that in setup. If the css and js show 404, feel free to create an Issue.

**Comment by pranay414** [comment] 2017-09-30 19:14
@codehimanshu yeah you missed the static files in setup.

**Comment by pranay414** [comment] 2017-09-30 19:56
@codehimanshu this issue has been fixed.

**Comment by saurabhranjan1806** [comment] 2017-09-30 20:32
the issue is fixed now

**Closed by saurabhranjan1806** 2017-09-30 20:32 UTC
Labels: hacktoberfest
